(define (domain delivery)
  (:requirements :strips)
  (:predicates (LOC ?x) (CRATE ?x)
	       (AGENT ?x)
	       (at-robby ?x)
	       (at-crate ?x ?y)
	       (free ?x) (carry ?x ?y)
	       )
  (:action move
	   :parameters (?x ?y)
	   :precondition (and (LOC ?x) (LOC ?y)
			      (at-robby ?x))
	   :effect (and (at-robby ?y)
			(not (at-robby ?x)))
	   )
  (:action pick-up
	   :parameters (?x ?y ?z)
	   :precondition (and (CRATE ?x) (LOC ?y) (AGENT ?z)
			      (at-crate ?x ?y) (at-robby ?y) (free ?z))
	   :effect (and (carry ?z ?x) (not (at-crate ?x ?y))
			(not (free ?z))))
  (:action drop
	   :parameters (?x ?y ?z)
	   :precondition (and (CRATE ?x) (LOC ?y) (AGENT ?z)
			      (carry ?z ?x) (at-robby ?y))
	   :effect (and (at-crate ?x ?y) (free ?z)
			(not (carry ?z ?x))))
  )
